#! /bin/sh

#команда для проверки скрипта#
#touch $HOME/aaaaaaaaaaaaaaaaaaaaaaaaa.txt 

wid=$1
class=$2
Chromium=$2
Bspwm=$2
instance=$3
consequences=$4

case "$Chromium" in
Chromium)
    echo "desktop=1 follow=off"
   ;;

esac
